[package]
name = "state_macros"
version = "0.2.0"
edition = "2024"
description = "A discrete event simulation library for Rust."
license = "GPL-3.0"
repository = "https://github.com/jamieyoung5/agsim"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.41"
syn = "2.0.107"
